openapi: 3.0.0
info:
  title: SPMI Test Swagger
  version: 1.0.0
servers:
  - url: https://simbe-dev.ulbi.ac.id
tags:
  - name: AMI Akreditasi LAMINFOKOM
paths:
  /api/v1/laminfokom/add:
    post:
      tags:
        - AMI Akreditasi LAMINFOKOM
      summary: Post Akreditasi LAMINFOKOM
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_sk_sertifikat: 1
                peringkat: Kedua
                konten: LAMINFOKOM adalah lembaga akreditasi kampus
                masa_berlaku_start: "2023-12-01"
                masa_berlaku_end: "2025-12-01"
                id_jenjang: 1
                id_prodi: 9
      parameters:
        - name: LOGIN
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDIzLTEyLTAxVDE2OjA5OjUwKzA3OjAwIiwiaWF0IjoiMjAyMy0xMi0wMVQxNDowOTo1MCswNzowMCIsImlkIjoiNjI4OTUyMjkxMDk2NiIsIm5iZiI6IjIwMjMtMTItMDFUMTQ6MDk6NTArMDc6MDAifbQZJNCenXldkexwdAiYRE7XSb2T4YqUW96_tXZ5QAAL1zfNZ7WeSBCG-aEyZJW4Hl9J7meo-wLb2WSKCf3qpAs
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/laminfokom:
    get:
      tags:
        - AMI Akreditasi LAMINFOKOM
      summary: Get All Akreditasi LAMINFOKOM
      parameters:
        - name: LOGIN
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDIzLTEyLTAxVDE2OjA5OjUwKzA3OjAwIiwiaWF0IjoiMjAyMy0xMi0wMVQxNDowOTo1MCswNzowMCIsImlkIjoiNjI4OTUyMjkxMDk2NiIsIm5iZiI6IjIwMjMtMTItMDFUMTQ6MDk6NTArMDc6MDAifbQZJNCenXldkexwdAiYRE7XSb2T4YqUW96_tXZ5QAAL1zfNZ7WeSBCG-aEyZJW4Hl9J7meo-wLb2WSKCf3qpAs
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/laminfokom/get:
    get:
      tags:
        - AMI Akreditasi LAMINFOKOM
      summary: Get By ID Akreditasi LAMINFOKOM
      parameters:
        - name: LOGIN
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDIzLTEyLTAxVDE2OjA5OjUwKzA3OjAwIiwiaWF0IjoiMjAyMy0xMi0wMVQxNDowOTo1MCswNzowMCIsImlkIjoiNjI4OTUyMjkxMDk2NiIsIm5iZiI6IjIwMjMtMTItMDFUMTQ6MDk6NTArMDc6MDAifbQZJNCenXldkexwdAiYRE7XSb2T4YqUW96_tXZ5QAAL1zfNZ7WeSBCG-aEyZJW4Hl9J7meo-wLb2WSKCf3qpAs
        - name: id_laminfokom
          in: query
          schema:
            type: integer
          example: "1"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/laminfokom/update:
    put:
      tags:
        - AMI Akreditasi LAMINFOKOM
      summary: Put Akreditasi LAMINFOKOM
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_sk_sertifikat: 1
                peringkat: Pertama
                konten: Coba update Akreditasi LAMINFOKOM
                masa_berlaku_start: "2023-11-30"
                masa_berlaku_end: "2025-11-30"
                id_jenjang: 1
                id_prodi: 9
      parameters:
        - name: LOGIN
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDIzLTEyLTAxVDE2OjA5OjUwKzA3OjAwIiwiaWF0IjoiMjAyMy0xMi0wMVQxNDowOTo1MCswNzowMCIsImlkIjoiNjI4OTUyMjkxMDk2NiIsIm5iZiI6IjIwMjMtMTItMDFUMTQ6MDk6NTArMDc6MDAifbQZJNCenXldkexwdAiYRE7XSb2T4YqUW96_tXZ5QAAL1zfNZ7WeSBCG-aEyZJW4Hl9J7meo-wLb2WSKCf3qpAs
        - name: id_laminfokom
          in: query
          schema:
            type: integer
          example: "2"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/laminfokom/delete:
    delete:
      tags:
        - AMI Akreditasi LAMINFOKOM
      summary: Delete Akreditasi LAMINFOKOM
      parameters:
        - name: LOGIN
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDIzLTEyLTAxVDE2OjA5OjUwKzA3OjAwIiwiaWF0IjoiMjAyMy0xMi0wMVQxNDowOTo1MCswNzowMCIsImlkIjoiNjI4OTUyMjkxMDk2NiIsIm5iZiI6IjIwMjMtMTItMDFUMTQ6MDk6NTArMDc6MDAifbQZJNCenXldkexwdAiYRE7XSb2T4YqUW96_tXZ5QAAL1zfNZ7WeSBCG-aEyZJW4Hl9J7meo-wLb2WSKCf3qpAs
        - name: id_laminfokom
          in: query
          schema:
            type: integer
          example: "2"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
